<?php

/**
 * Implements hook_block_info().
 *
 * This hook declares what blocks are provided by the module.
 */
function commerce_kickstart_content_block_info() {
  $blocks['social'] = array(
    'info' => t('Social links'),
    'weight' => '0',
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  $blocks['payment'] = array(
    'info' => t('Payment methods'),
    'weight' => '0',
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  $blocks['shipping'] = array(
    'info' => t('Shipping'),
    'weight' => '0',
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  return $blocks;
}

/**
 * Implements hook_block_configure().
 *
 * This hook declares configuration options for blocks provided by this module.
 */
function commerce_kickstart_content_block_configure($delta = '') {
  $form = array();
  switch ($delta) {
    case 'social':
      $form['block_social_content'] = array(
        '#type' => 'text_format',
        '#format' => 'full_html',
        '#title' => t('Block body'),
        '#size' => 60,
        '#description' => t('List of social website you\'re on.'),
        '#default_value' => variable_get('block_social_content', ''),
      );
      break;
    case 'payment':
      $form['block_payment_content'] = array(
        '#type' => 'text_format',
        '#format' => 'full_html',
        '#title' => t('Block body'),
        '#size' => 60,
        '#description' => t('List all the available payment methods'),
        '#default_value' => variable_get('block_payment_content', ''),
      );
      break;
    case 'shipping':
      $form['block_shipping_message'] = array(
        '#type' => 'textfield',
        '#title' => t('Message'),
        '#size' => 100,
        '#maxlength' => 128,
        '#description' => t('Display a short message on homepage'),
        '#default_value' => variable_get('block_shipping_message'),
      );
      $form['block_shipping_amount'] = array(
        '#type' => 'textfield',
        '#title' => t('Amount'),
        '#size' => 10,
        '#maxlength' => 10,
        '#description' => t('Amount should be a numeric value'),
        '#default_value' => variable_get('block_shipping_amount'),
      );
      break;
    default:
      break;
  }
  return $form;
}

/**
 * Implements hook_block_save().
 *
 * This hook declares how the configured options for a block
 * provided by this module are saved.
 */
function commerce_kickstart_content_block_save($delta = '', $edit = array()) {
  // We need to save settings from the configuration form.
  switch ($delta) {
    case 'social':
      variable_set('block_social_content', $edit['block_social_content']);
      break;
    case 'payment':
      variable_set('block_payment_content', $edit['block_payment_content']);
      break;
    case 'shipping':
      variable_set('block_shipping_message', $edit['block_shipping_message']);
      variable_set('block_shipping_amount', $edit['block_shipping_amount']);
      break;
    default:
      break;
  }
  return;
}

/**
 * Implements hook_block_view().
 *
 * This hook generates the contents of the blocks themselves.
 */
function commerce_kickstart_content_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'social':
      $block['subject'] = t('Connect with us');
      $block['content'] = commerce_kickstart_content_contents($delta);
      break;
    case 'payment':
      $block['subject'] = NULL;
      $block['content'] = commerce_kickstart_content_contents($delta);
      break;
    case 'shipping':
      $block['subject'] = NULL;
      $block['content'] = commerce_kickstart_content_contents($delta);
      break;
    default:
      break;
  }
  return $block;
}

/**
 * A module-defined block content function.
 */
function commerce_kickstart_content_contents($which_block) {
  switch ($which_block) {
    case 'social':
      $block = "<ul id=\"social\">\n";
      $block .= "\t<li id=\"facebook\">" . t('Like us on Facebook') . "</li>\n";
      $block .= "\t<li id=\"twitter\">" . t('Follow Us on Twitter') . "</li>\n";
      $block .= "\t<li id=\"pinterest\">" . t('What We Like on Pinterest') . "</li>\n";
      $block .= "</ul>\n";

      $variable = variable_get('block_social_content');
      if (empty($variable)) {
        variable_set('block_social_content', $block);
      }
      return variable_get('block_social_content', $block);
    case 'payment':
      $block = "<ul id=\"payments\">\n";
      $block .= "\t<li><span id=\"payment_visa_premier\">" . t('Visa premier') . "</span></li>\n";
      $block .= "\t<li><span id=\"payment_paypal\">" . t('Paypal') . "</span></li>\n";
      $block .= "\t<li><span id=\"payment_mastercard\">" . t('Mastercard') . "</span></li>\n";
      $block .= "\t<li><span id=\"payment_american_express\">" . t('American express') . "</span></li>\n";
      $block .= "\t<li><span id=\"payment_visa\">" . t('Visa') . "</span></li>\n";
      $block .= "</ul>\n";

      $variable = variable_get('block_payment_content');
      if (empty($variable)) {
        variable_set('block_payment_content', $block);
      }
      return variable_get('block_payment_content', $block);
    case 'shipping':
      $message = variable_get('block_shipping_message', 'Free shipping on order over');
      $amount = variable_get('block_shipping_amount', '99');

      $block = "<div id=\"shipping\">\n";
      $block .= "\t<span id=\"shipping_message\">" . $message . "</span>\n";
      $block .= "\t<span id=\"shipping_currency\">" .commerce_currency_format($amount, commerce_default_currency()) . "</span>\n";
      $block .= "</div>\n";

      return $block;
    default:
      // It is possible that a block not have any content, since it is
      // probably dynamically constructed. In this case, Drupal will not display
      // the block at all. This block will not be displayed.
      return;
  }
}
