<?php

/**
 * Implements hook_block_info().
 *
 * This hook declares what blocks are provided by the module.
 */
function commerce_kickstart_content_block_info() {
  $blocks['social'] = array(
    'info' => t('Social links'),
    'weight' => '0',
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  $blocks['payment'] = array(
    'info' => t('Payment methods'),
    'weight' => '0',
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  $blocks['shipping_discount'] = array(
    'info' => t('Shipping discount'),
    'weight' => '0',
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  $blocks['promotional_banner'] = array(
    'info' => t('Promotional banner'),
    'weight' => '0',
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  $blocks['powered_drupal_commerce'] = array(
    'info' => t('Powered by Drupal Commerce'),
    'weight' => '0',
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  return $blocks;
}

/**
 * Implements hook_block_configure().
 *
 * This hook declares configuration options for blocks provided by this module.
 */
function commerce_kickstart_content_block_configure($delta = '') {
  $form = array();
  switch ($delta) {
    case 'social':
      $form['block_social_content'] = array(
        '#type' => 'text_format',
        '#format' => 'full_html',
        '#title' => t('Block body'),
        '#size' => 60,
        '#description' => t('List of social website you\'re on.'),
        '#default_value' => variable_get('block_social_content'),
      );
      break;
    case 'payment':
      $form['block_payment_content'] = array(
        '#type' => 'text_format',
        '#format' => 'full_html',
        '#title' => t('Block body'),
        '#size' => 60,
        '#description' => t('List all the available payment methods'),
        '#default_value' => variable_get('block_payment_content'),
      );
      break;
    case 'shipping_discount':
      $form['block_shipping_discount_message'] = array(
        '#type' => 'text_format',
        '#format' => 'full_html',
        '#title' => t('Message'),
        '#size' => 60,
        '#description' => t('Display a short message on homepage. To display amout use @amount placeholders'),
        '#default_value' => variable_get('block_shipping_discount_message'),
      );
      $form['block_shipping_discount_amount'] = array(
        '#type' => 'textfield',
        '#title' => t('Amount'),
        '#size' => 10,
        '#maxlength' => 10,
        '#description' => t('Amount should be a numeric value'),
        '#default_value' => variable_get('block_shipping_discount_amount'),
      );
      break;
    case 'promotional_banner':
      $form['block_promotional_banner_content'] = array(
        '#type' => 'text_format',
        '#format' => 'full_html',
        '#title' => t('Block body'),
        '#size' => 60,
        '#description' => t('Display a promotional message'),
        '#default_value' => variable_get('block_promotional_banner_content'),
      );
      break;
    default:
      break;
  }
  return $form;
}

/**
 * Implements hook_block_save().
 *
 * This hook declares how the configured options for a block
 * provided by this module are saved.
 */
function commerce_kickstart_content_block_save($delta = '', $edit = array()) {
  // We need to save settings from the configuration form.
  switch ($delta) {
    case 'social':
      variable_set('block_social_content', $edit['block_social_content']['value']);
      break;
    case 'payment':
      variable_set('block_payment_content', $edit['block_payment_content']['value']);
      break;
    case 'shipping_discount':
      variable_set('block_shipping_discount_message', $edit['block_shipping_discount_message']['value']);
      variable_set('block_shipping_discount_amount', $edit['block_shipping_discount_amount']);
      break;
    case 'promotional_banner':
      variable_set('block_promotional_banner_content', $edit['block_promotional_banner_content']['value']);
      break;
    default:
      break;
  }
  return;
}

/**
 * Implements hook_block_view().
 *
 * This hook generates the contents of the blocks themselves.
 */
function commerce_kickstart_content_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'social':
      $block['subject'] = t('Connect with us');
      $block['content'] = commerce_kickstart_content_contents($delta);
      break;
    case 'payment':
      $block['subject'] = NULL;
      $block['content'] = commerce_kickstart_content_contents($delta);
      break;
    case 'shipping_discount':
      $block['subject'] = NULL;
      $block['content'] = commerce_kickstart_content_contents($delta);
      break;
    case 'promotional_banner':
      $block['subject'] = NULL;
      $block['content'] = commerce_kickstart_content_contents($delta);
      break;
    case 'powered_drupal_commerce':
      $block['subject'] = NULL;
      $block['content'] = commerce_kickstart_content_contents($delta);
      break;
    default:
      break;
  }
  return $block;
}

/**
 * A module-defined block content function.
 */
function commerce_kickstart_content_contents($which_block) {
  switch ($which_block) {
    case 'social':
      $block = variable_get('block_social_content');
      if (empty($block)) {
        $block = "<ul id=\"social\">\n";
        $block .= "\t<li><a href=\"https://www.facebook.com/commerceguys\" id=\"facebook\">Like us on Facebook</a></li>\n";
        $block .= "\t<li><a href=\"https://twitter.com/commerceguys\" id=\"twitter\">Follow Us on Twitter</a></li>\n";
        $block .= "\t<li><span id=\"pinterest\">What We Like on Pinterest</span></li>\n";
        $block .= "</ul>\n";
        variable_set('block_social_content', $block);
      }
      return $block;
    case 'payment':
      $block = variable_get('block_payment_content');
      if (empty($block)) {
        $block = "<ul id=\"payments\">\n";
        $block .= "\t<li><span id=\"payment_visa_premier\">" . t('Visa premier') . "</span></li>\n";
        $block .= "\t<li><span id=\"payment_paypal\">" . t('Paypal') . "</span></li>\n";
        $block .= "\t<li><span id=\"payment_mastercard\">" . t('Mastercard') . "</span></li>\n";
        $block .= "\t<li><span id=\"payment_american_express\">" . t('American express') . "</span></li>\n";
        $block .= "\t<li><span id=\"payment_visa\">" . t('Visa') . "</span></li>\n";
        $block .= "</ul>\n";
        variable_set('block_payment_content', $block);
      }
      return $block;
    case 'shipping_discount':
      $amount = variable_get('block_shipping_discount_amount');
      if (empty($amount)) {
        $amount = '99';
        variable_set('block_shipping_discount_amount', $amount);
      }

      $message = variable_get('block_shipping_discount_message');
      if (empty($message)) {
        $message = "<div id=\"shipping\">\n";
        $message .= "\t<span id=\"shipping_message\"><span><em>Free</em> shipping</span> on orders over</span>\n";
        $message .= "\t<span id=\"shipping_currency\">@amount</span>\n";
        $message .= "</div>\n";
        variable_set('block_shipping_discount_message', $message);
      }
      $block = format_string($message, array('@amount' => commerce_currency_format($amount, commerce_default_currency())));
      return $block;
    case 'promotional_banner':
      $block = variable_get('block_promotional_banner_content');
      if (empty($block)) {
        $block = "<div id=\"promotional_banner\">\n";
        $block .= "\t<span><span class='promotional_banner_saving'>SAVE 25%</span> Purchases made between June 5 - 12 will be discounted <span class='promotional_banner_special_offer'>Offer Details</span></span>\n";
        $block .= "</div>\n";
        variable_set('block_promotional_banner_content', $block);
      }
      return $block;
    case 'powered_drupal_commerce':
      $block = "\t<span id=\"powered_by_drupal_commerce\">Powered by <a href=\"http://www.drupalcommerce.org\">Drupal Commerce</a></span>\n";
      return $block;
    default:
      // It is possible that a block not have any content, since it is
      // probably dynamically constructed. In this case, Drupal will not display
      // the block at all. This block will not be displayed.
      return;
  }
}

/**
 * Implements hook_preprocess_page().
 */
function commerce_kickstart_content_preprocess_page(&$variables) {
  if (drupal_is_front_page()) {
    // Remove the title from this page.
    $variables['title'] = '';
  }
  if (arg(0) == 'taxonomy' && arg(1) == 'term' && is_numeric(arg(2))) {
    // Remove collection_taxonomy_term view title.
    $variables['title'] = '';
 }
}
