<?php
/**
 * @file
 * Code for the Commerce kickstart settings feature.
 */

include_once('commerce_kickstart_settings.features.inc');

/**
 * Implements hook_entity_info_alter().
 * Create new view mode for product display, commerce product.
 */
function commerce_kickstart_settings_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['product_list'] = array(
    'label' => t('Product list'),
    'custom settings' => TRUE,
  );
  $entity_info['commerce_product']['view modes']['node_product_list'] = array(
    'label' => t('Node: Product list'),
    'custom settings' => TRUE,
  );
}

/**
 * Implements hook_theme().
 */
function commerce_kickstart_settings_theme() {
  $themes = array();
  foreach (entity_get_info() as $entity_type => $entity_info) {
    foreach ($entity_info['bundles'] as $bundle => $bundle_info) {
      foreach ($entity_info['view modes'] as $view_mode => $view_mode_info) {
        $themes["{$entity_type}__{$bundle}__{$view_mode}"] = array(
          'render element' => 'elements',
        );
      }
    }
  }
  return $themes;
}

function commerce_kickstart_settings_block_info_alter(&$blocks, $theme, $code_blocks) {

  $default_theme = variable_get('theme_default');
  if ($theme == $default_theme) {
    if(isset($blocks['views']) && !empty($blocks['views'])) {
      // Block Last news post.
      $blocks['views']['demo_content-block_1']['status'] = 1;
      $blocks['views']['demo_content-block_1']['visibility'] = 1;
      $blocks['views']['demo_content-block_1']['region'] = 'postscript_first';
      $blocks['views']['demo_content-block_1']['pages'] = '<front>';

      // Block Last blog post.
      $blocks['views']['demo_content-block_2']['status'] = 1;
      $blocks['views']['demo_content-block_2']['visibility'] = 1;
      $blocks['views']['demo_content-block_2']['region'] = 'postscript_second';
      $blocks['views']['demo_content-block_2']['pages'] = '<front>';

      // Block Last brand post.
      $blocks['views']['demo_content-block_3']['status'] = 1;
      $blocks['views']['demo_content-block_3']['visibility'] = 1;
      $blocks['views']['demo_content-block_3']['pages'] = '<front>';
      $blocks['views']['demo_content-block_3']['region'] = 'postscript_third';

      // Block HP Slideshow.
      $blocks['views']['demo_content-block_4']['status'] = 1;
      $blocks['views']['demo_content-block_4']['visibility'] = 1;
      $blocks['views']['demo_content-block_4']['pages'] = '<front>';
      $blocks['views']['demo_content-block_4']['region'] = 'content';
    }

    // Menu footer navigation.
    $blocks['menu']['menu-footer-navigation']['title'] = '<none>';
    $blocks['menu']['menu-footer-navigation']['status'] = 1;
    $blocks['menu']['menu-footer-navigation']['region'] = 'footer_first';

    // Menu user.
    $blocks['system']['user-menu']['title'] = '<none>';
    $blocks['system']['user-menu']['status'] = 1;
    $blocks['system']['user-menu']['region'] = 'user_first';
  }
}
