<?php
/**
 * @file
 * Code for the kickstart_view_modes feature.
 */

/**
 * Implements hook_entity_info_alter().
 */
function kickstart_view_modes_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['product_list'] = array(
    'label' => t('Product list'),
    'custom settings' => TRUE,
  );
  $entity_info['commerce_product']['view modes']['node_product_list'] = array(
    'label' => t('Node: Product list'),
    'custom settings' => TRUE,
  );
}

/**
 * Implements hook_theme().
 */
function kickstart_view_modes_theme() {
  $themes = array();
  foreach (entity_get_info() as $entity_type => $entity_info) {
    foreach ($entity_info['bundles'] as $bundle => $bundle_info) {
      foreach ($entity_info['view modes'] as $view_mode => $view_mode_info) {
        $themes["{$entity_type}__{$bundle}__{$view_mode}"] = array(
          'render element' => 'elements',
        );
      }
    }
  }
  return $themes;
}
