<?php
/**
 * @file
 * Code for the demo_features module.
 */

/**
 * Custom function which pickup terms from a vocabulary
 * and render it into a link with a custom path.
 */
function _demo_features_menu_with_taxonomy($vid, $path) {
  $terms = taxonomy_get_tree($vid, 0, NULL, FALSE);
  $menu[] = l('Home', '<front>');
  foreach ($terms as $term) {
    $menu[] .= l($term->name, $path . '/' . $term->tid);
  }
  $menu[] .= l('All products', 'display-all-products');
  return theme('item_list', array('items' => $menu));
}

/**
  * Implements hook_block_info().
  */
 function demo_features_block_info() {
   $blocks['demo_menu'] = array(
     'info' => t('Demo dynamic menu'),
     'weight' => '10',
     'cache' => DRUPAL_NO_CACHE,
   );
   return $blocks;
 }

/**
 * Implements hook_block_view().
 *
 * Generate a block with a custom menu.
 */
function demo_features_block_view($delta = '') {
  $block['subject'] = NULL;
  $block['content'] = _demo_features_menu_with_taxonomy('5', 'products');
  return $block;
}

