<?php

/**
 * Implements hook_menu().
 */
function demo_menu() {
  $items = array();
  $items['admin/demo'] = array(
    'title' => 'Manage demo',
    'description' => 'todo.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('demo_kill_me_form'),
    'access callback' => TRUE,
    //'access callback' => 'commerce_product_ui_product_add_any_access',
    'weight' => 10,
  );
  $items['admin/demo/disable'] = array(
    'title' => 'Manage demo',
    'description' => 'todo.',
    'page callback' => 'demo_disable_me',
    'access callback' => TRUE,
    //'access callback' => 'commerce_product_ui_product_add_any_access',
    'weight' => 10,
  );
  return $items;
}

/**
 * Menu callback.
 */
function demo_kill_me_form() {
  $form['message'] = array(
    '#type' => 'item',
    '#markup' => 'Warning : Your are going to wipe all content from this site',
  );
  $form['buttons']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Kill me !'),
  );
  return $form;
}

/**
 * Submit function for demo_kill_me_form().
 *
 * @param $form
 * @param $form_state
 */
function demo_kill_me_form_submit($form, &$form_state) {
  // Take care of database prefix if we use one.
  $databases = Database::getConnectionInfo('default');
  $database = $databases['default'];
  $prefix = !empty($database['prefix']['default']) ? $database['prefix']['default'] : '';

  $tables = db_find_tables($prefix . '%');

  foreach($tables as $table) {
    db_drop_table($table);
  }
  include_once DRUPAL_ROOT . '/includes/install.inc';
  install_goto('install.php?profile=commerce_kickstart&locale=en');
}


/**
 * Disable demo module.
 */
function  demo_disable_me() {
  module_disable(array('demo'));
  variable_set('menu_rebuild_needed', TRUE);
}

/**
 * Implements hook_page_alter().
 */
function demo_page_alter(&$page) {
  $message = 'You are in commerce kickstart demo mode';
  $kill_url = url('admin/demo', array('absolute' => TRUE));
  $disable_url = url('admin/demo/disable', array('absolute' => TRUE));
  $icon_path = url(drupal_get_path('module', 'demo') . '/images/', array('absolute' => TRUE));
  $tooltip = advanced_help_view_topic('demo', 'tooltip');

  $settings = array(
    'demo' => array(
      'message' => filter_xss_admin($message),
      'tooltip' => filter_xss_admin($tooltip),
      'icons_path' => $icon_path,
      'kill_url' => $kill_url,
      'disable_url' => $disable_url,
    )
  );
  drupal_add_js($settings, 'setting');
  drupal_add_js(drupal_get_path('module', 'demo') . '/demo.js');
}

