<?php
/**
 * @file
 * Code for the Feature CK2 Front feature.
 */

include_once('feature_ck2_demo.features.inc');

function feature_ck2_demo_block_info_alter(&$blocks, $theme, $code_blocks) {

  $default_theme = variable_get('theme_default');
  if ($theme == $default_theme) {
    if(isset($blocks['views']) && !empty($blocks['views'])) {
      // Block Last news post.
      $blocks['views']['demo_content-block_1']['status'] = 1;
      $blocks['views']['demo_content-block_1']['visibility'] = 1;
      $blocks['views']['demo_content-block_1']['region'] = 'postscript_first';
      $blocks['views']['demo_content-block_1']['pages'] = '<front>';

      // Block Last blog post.
      $blocks['views']['demo_content-block_2']['status'] = 1;
      $blocks['views']['demo_content-block_2']['visibility'] = 1;
      $blocks['views']['demo_content-block_2']['region'] = 'postscript_second';
      $blocks['views']['demo_content-block_2']['pages'] = '<front>';

      // Block Last brand post.
      $blocks['views']['demo_content-block_3']['status'] = 1;
      $blocks['views']['demo_content-block_3']['visibility'] = 1;
      $blocks['views']['demo_content-block_3']['pages'] = '<front>';
      $blocks['views']['demo_content-block_3']['region'] = 'postscript_third';

      // Block HP Slideshow.
      $blocks['views']['demo_content-block_4']['status'] = 1;
      $blocks['views']['demo_content-block_4']['visibility'] = 1;
      $blocks['views']['demo_content-block_4']['pages'] = '<front>';
      $blocks['views']['demo_content-block_4']['region'] = 'content';
    }

    // Menu footer navigation.
    $blocks['menu']['menu-footer-navigation']['title'] = '<none>';
    $blocks['menu']['menu-footer-navigation']['status'] = 1;
    $blocks['menu']['menu-footer-navigation']['region'] = 'footer_first';

    // Menu user.
    $blocks['system']['user-menu']['title'] = '<none>';
    $blocks['system']['user-menu']['status'] = 1;
    $blocks['system']['user-menu']['region'] = 'user_first';
  }
}