<?php
/**
 * @file
 * Code for the Commerce Kickstart Blog UI.
 */

include_once 'commerce_kickstart_blog_ui.features.inc';

/**
 * Implements hook_translated_menu_link_alter().
 */
function commerce_kickstart_blog_ui_translated_menu_link_alter(&$item, $map) {
  // Hide the "User account" link for anonymous users.
  if ($item['menu_name'] == 'menu-kickstart-user-menu' && $item['link_path'] == 'user' && user_is_anonymous()) {
    $item['hidden'] = 1;
  }
}

/**
 * Override or insert variables into the page template.
 */
function commerce_kickstart_blog_ui_preprocess_node(&$vars) {
  if ($vars['type'] == 'blog_post' && $vars['view_mode'] == 'teaser') {
    if ($vars['comment'] != COMMENT_NODE_HIDDEN) {
      unset($vars['content']['links']['comment']['#links']['comment-add']);
      if (empty($vars['comment_count'])) {
        $vars['content']['links']['comment']['#links']['comment-comments'] = array (
          'title' => t('0 <span>comment</span>'),
          'href' => 'node/' . $vars['nid'],
          'attributes' => array('title' => t('Be the first to add a comment'),),
          'fragment' => 'comment-form',
          'html' => TRUE,
        );
      }
      else {
        $vars['content']['links']['comment']['#links']['comment-comments'] = array(
          'title' => format_plural($vars['comment_count'], '1 <span>comment</span>', '@count <span>comments</span>'),
          'href' => 'node/' . $vars['nid'],
          'attributes' => array('title' => t('Jump to the first comment of this posting.')),
          'fragment' => 'comments',
          'html' => TRUE,
        );
        if ($new = comment_num_new($vars['nid'])) {
          $vars['content']['links']['comment']['#links']['comment-new-comments'] = array(
            'title' => format_plural($new, '1 <span>new comment</span>', '@count <span>new comments</span>'),
            'href' => 'node/' . $vars['nid'],
            'query' => comment_new_page_count($vars['comment_count'], $new, $vars['node']),
            'attributes' => array('title' => t('Jump to the first new comment of this posting.')),
            'fragment' => 'new',
            'html' => TRUE,
          );
        }
      }
    }
  }
}
